// Tradition-specific timeline templates
// These templates are automatically added when a couple selects their cultural tradition

export interface TimelineTemplate {
  time: string;
  title: string;
  icon: 'heart' | 'camera' | 'music' | 'users' | 'coffee' | 'sun' | 'moon' | 'star';
  description?: string;
}

export const TIMELINE_TEMPLATES: Record<string, TimelineTemplate[]> = {
  norway: [
    { time: "10:00", title: "Forberedelser", icon: "heart", description: "Brudens og brudgommens forberedelser" },
    { time: "14:00", title: "Vielse", icon: "users", description: "Kirkelig vielse" },
    { time: "14:30", title: "Gratulering", icon: "heart", description: "Gratulasjon utenfor kirken" },
    { time: "15:00", title: "Fotosession", icon: "camera", description: "Brudepar- og familiebilder" },
    { time: "16:00", title: "Cocktail", icon: "coffee", description: "Mingling og forfriskninger" },
    { time: "17:00", title: "Middag", icon: "coffee", description: "Bryllupsmiddag" },
    { time: "19:00", title: "Taler", icon: "users", description: "Taler og skåler" },
    { time: "20:00", title: "Kransekake", icon: "heart", description: "Kransekake-seremoni" },
    { time: "20:30", title: "Brudevalsen", icon: "music", description: "Første dans" },
    { time: "21:00", title: "Dans og fest", icon: "music", description: "Feiring til sent på kvelden" },
  ],
  sweden: [
    { time: "10:00", title: "Förberedelser", icon: "heart", description: "Förberedelser" },
    { time: "14:00", title: "Vigsel", icon: "users", description: "Vigselceremoni" },
    { time: "14:30", title: "Gratulationer", icon: "heart", description: "Gratulationer utanför" },
    { time: "15:00", title: "Fotosession", icon: "camera", description: "Brudpar- och familjefoton" },
    { time: "16:00", title: "Mingel", icon: "coffee", description: "Mingel och förfriskningar" },
    { time: "17:00", title: "Middag", icon: "coffee", description: "Bryllupsmiddag" },
    { time: "19:00", title: "Tal", icon: "users", description: "Tal och skålar" },
    { time: "20:00", title: "Prinsesstårta", icon: "heart", description: "Bröllopstårta" },
    { time: "20:30", title: "Första dansen", icon: "music", description: "Brudparets första dans" },
    { time: "21:00", title: "Dans", icon: "music", description: "Dans och fest" },
  ],
  denmark: [
    { time: "10:00", title: "Forberedelser", icon: "heart", description: "Brudens og gommens forberedelser" },
    { time: "14:00", title: "Vielse", icon: "users", description: "Vielsesceremoni" },
    { time: "14:30", title: "Lykønskning", icon: "heart", description: "Tillykke udenfor" },
    { time: "15:00", title: "Fotosession", icon: "camera", description: "Brudepar- og familiebilleder" },
    { time: "16:00", title: "Reception", icon: "coffee", description: "Reception og forfriskninger" },
    { time: "17:00", title: "Middag", icon: "coffee", description: "Bryllupsmiddag" },
    { time: "19:00", title: "Taler og sange", icon: "users", description: "Bryllupstaler og sange" },
    { time: "20:00", title: "Bryllupskage", icon: "heart", description: "Bryllupskringle" },
    { time: "20:30", title: "Brudevals", icon: "music", description: "Første dans" },
    { time: "21:00", title: "Dans", icon: "music", description: "Dans og fest" },
  ],
  hindu: [
    { time: "06:00", title: "Ganesh Puja", icon: "star", description: "Bønn for å fjerne hindringer" },
    { time: "07:00", title: "Madhuparka", icon: "coffee", description: "Brudgommens velkomst" },
    { time: "08:00", title: "Kanyadaan", icon: "users", description: "Farens gave av bruden" },
    { time: "09:00", title: "Agni Poojan", icon: "sun", description: "Hellig ildseremoni" },
    { time: "10:00", title: "Saptapadi", icon: "heart", description: "De syv skritt rundt ilden" },
    { time: "11:00", title: "Mangalsutra", icon: "heart", description: "Hellig halskjede" },
    { time: "12:00", title: "Sindoor", icon: "star", description: "Rød farge i hårskillen" },
    { time: "13:00", title: "Lunch & Velsignelser", icon: "coffee", description: "Måltid og velsignelser fra eldre" },
    { time: "14:00", title: "Fotosession", icon: "camera", description: "Familie- og brudepar-bilder" },
    { time: "16:00", title: "Reception", icon: "users", description: "Reception for gjester" },
    { time: "18:00", title: "Middag", icon: "coffee", description: "Festmiddag" },
    { time: "20:00", title: "Vidai", icon: "moon", description: "Brudens avskjed fra hjemmet" },
  ],
  sikh: [
    { time: "07:00", title: "Anand Karaj forberedelse", icon: "sun", description: "Morgenforberedelser" },
    { time: "09:00", title: "Milni", icon: "users", description: "Familienes møte" },
    { time: "10:00", title: "Anand Karaj", icon: "heart", description: "Vielse i Gurdwara" },
    { time: "11:00", title: "Laavan - Første runde", icon: "star", description: "Første runde rundt Guru Granth Sahib" },
    { time: "11:15", title: "Laavan - Andre runde", icon: "star", description: "Andre runde - disiplin" },
    { time: "11:30", title: "Laavan - Tredje runde", icon: "star", description: "Tredje runde - spiritualitet" },
    { time: "11:45", title: "Laavan - Fjerde runde", icon: "star", description: "Fjerde runde - harmoni" },
    { time: "12:00", title: "Palla-seremoni", icon: "heart", description: "Sjal som binder paret" },
    { time: "12:30", title: "Karah Parshad", icon: "coffee", description: "Hellig søt pudding" },
    { time: "13:00", title: "Langar", icon: "coffee", description: "Fellesskap måltid i Gurdwara" },
    { time: "15:00", title: "Fotosession", icon: "camera", description: "Familie- og brudepar-bilder" },
    { time: "18:00", title: "Reception", icon: "users", description: "Kveldsmottak for gjester" },
    { time: "20:00", title: "Doli", icon: "moon", description: "Brudens avreise" },
  ],
  muslim: [
    { time: "10:00", title: "Forberedelser", icon: "heart", description: "Brudens og brudgommens forberedelser" },
    { time: "14:00", title: "Mehndi (valgfritt)", icon: "star", description: "Henna-seremoni for bruden" },
    { time: "16:00", title: "Nikah forberedelse", icon: "users", description: "Forberedelse til vielse" },
    { time: "17:00", title: "Nikah", icon: "heart", description: "Islamsk vielse med imam og vitner" },
    { time: "17:30", title: "Mehr-gave", icon: "star", description: "Brudgommens gave til bruden" },
    { time: "18:00", title: "Du'a", icon: "sun", description: "Bønner og velsignelser" },
    { time: "18:30", title: "Gratulering", icon: "users", description: "Gratulasjon fra familie og venner" },
    { time: "19:00", title: "Fotosession", icon: "camera", description: "Familie- og brudepar-bilder" },
    { time: "20:00", title: "Walima", icon: "coffee", description: "Bryllupsfest arrangert av brudgommen" },
    { time: "21:00", title: "Middag", icon: "coffee", description: "Festmåltid for alle gjester" },
    { time: "23:00", title: "Rukhsati", icon: "moon", description: "Brudens avskjed fra familien" },
  ],
  jewish: [
    { time: "10:00", title: "Forberedelser", icon: "heart", description: "Brudens og brudgommens forberedelser" },
    { time: "14:00", title: "Kabbalat Panim", icon: "users", description: "Gjeste-mottakelse" },
    { time: "15:00", title: "Tisch", icon: "coffee", description: "Brudgommens bord" },
    { time: "15:30", title: "Bedeken", icon: "heart", description: "Slørlegging av bruden" },
    { time: "16:00", title: "Prosesjon", icon: "users", description: "Prosesjon til Chuppah" },
    { time: "16:15", title: "Circling", icon: "star", description: "Bruden går rundt brudgommen 7 ganger" },
    { time: "16:30", title: "Ketubah-signering", icon: "heart", description: "Ekteskapskontrakten leses og signeres" },
    { time: "16:45", title: "Sheva Brachot", icon: "sun", description: "De syv velsignelsene" },
    { time: "17:00", title: "Glass-knusing", icon: "star", description: "Brudgommen knuser glasset" },
    { time: "17:15", title: "Yichud", icon: "heart", description: "Privatøyeblikk for brudeparet" },
    { time: "18:00", title: "Fotosession", icon: "camera", description: "Familie- og brudepar-bilder" },
    { time: "19:00", title: "Reception", icon: "users", description: "Festmottak" },
    { time: "20:00", title: "Middag", icon: "coffee", description: "Bryllupsmiddag" },
    { time: "22:00", title: "Hora-dans", icon: "music", description: "Tradisjonell jødisk dans" },
  ],
  chinese: [
    { time: "07:00", title: "Hårpynt-seremoni", icon: "heart", description: "Brudens hår og sminke" },
    { time: "08:00", title: "Brudgommen henter bruden", icon: "users", description: "Dør-spill og hindringer" },
    { time: "09:00", title: "Te-seremoni", icon: "coffee", description: "Servering av te til eldre familiemedlemmer" },
    { time: "10:00", title: "Hårbøying", icon: "star", description: "Bruden bøyer seg for forfedre" },
    { time: "11:00", title: "Røde konvolutter", icon: "heart", description: "Hongbao fra eldre" },
    { time: "12:00", title: "Fotosession", icon: "camera", description: "Brudepar- og familiebilder" },
    { time: "14:00", title: "Ankomst til bankett", icon: "users", description: "Gjestenes ankomst" },
    { time: "15:00", title: "Bryllups-bankett", icon: "coffee", description: "Tradisjonelt 8-retters måltid" },
    { time: "16:00", title: "Kjole-skift", icon: "heart", description: "Bruden bytter til Qipao/Cheongsam" },
    { time: "17:00", title: "Skåler rundt bordene", icon: "users", description: "Brudeparet skåler med gjestene" },
    { time: "18:00", title: "Lykke-spill", icon: "star", description: "Tradisjonelle bryllupsleker" },
    { time: "19:00", title: "Avskjed", icon: "moon", description: "Takk til gjestene" },
  ],
};

// Default generic timeline (if no tradition selected)
export const DEFAULT_TIMELINE: TimelineTemplate[] = [
  { time: "10:00", title: "Forberedelser", icon: "heart", description: "Brudens og brudgommens forberedelser" },
  { time: "14:00", title: "Vielse", icon: "users", description: "Vielsesseremoni" },
  { time: "14:30", title: "Gratulering", icon: "heart", description: "Gratulasjon" },
  { time: "15:00", title: "Fotosession", icon: "camera", description: "Bilder av brudeparet" },
  { time: "16:00", title: "Cocktail", icon: "coffee", description: "Mingling" },
  { time: "17:00", title: "Middag", icon: "coffee", description: "Bryllupsmiddag" },
  { time: "19:00", title: "Taler", icon: "users", description: "Taler og skåler" },
  { time: "20:00", title: "Bryllupskake", icon: "heart", description: "Kake-seremoni" },
  { time: "20:30", title: "Første dans", icon: "music", description: "Brudeparets første dans" },
  { time: "21:00", title: "Dans og fest", icon: "music", description: "Fest" },
];
