/**
 * Evendi Music Matcher MVP E2E tests (API-level)
 */
import { test, expect, APIRequestContext } from '@playwright/test';
import {
  EVENDI_URL,
  getCoupleAuth,
  coupleHeaders,
  getVendorToken,
  vendorHeaders,
} from './helpers';

const BASE = EVENDI_URL;

async function ensureAcceptedOffer(params: {
  request: APIRequestContext;
  coupleToken: string;
  coupleId: string;
  vendorToken: string;
}): Promise<string> {
  const { request, coupleToken, coupleId, vendorToken } = params;

  const vendorOffersRes = await request.get(`${BASE}/api/vendor/offers`, {
    headers: vendorHeaders(vendorToken),
  });
  if (vendorOffersRes.status() !== 200) {
    throw new Error(`Failed to fetch vendor offers: ${vendorOffersRes.status()}`);
  }

  const vendorOffers = await vendorOffersRes.json() as Array<{
    id: string;
    status: string;
    couple?: { id?: string } | null;
  }>;
  const accepted = vendorOffers.find((offer) => offer.status === "accepted" && offer.couple?.id === coupleId);
  if (accepted) return accepted.id;

  const pending = vendorOffers.find((offer) => offer.status === "pending" && offer.couple?.id === coupleId);
  let offerId = pending?.id || "";

  if (!offerId) {
    const createOfferRes = await request.post(`${BASE}/api/vendor/offers`, {
      headers: vendorHeaders(vendorToken),
      data: {
        coupleId,
        title: `E2E Offer ${Date.now()}`,
        message: "Autogenerated for music matcher e2e",
        items: [
          {
            title: "E2E Music Package",
            quantity: 1,
            unitPrice: 15000,
          },
        ],
      },
    });

    if (createOfferRes.status() !== 201) {
      const body = await createOfferRes.json().catch(() => ({}));
      throw new Error(`Failed to create vendor offer: ${createOfferRes.status()} ${JSON.stringify(body)}`);
    }

    const createdOffer = await createOfferRes.json() as { id: string };
    offerId = createdOffer.id;
  }

  const respondRes = await request.post(`${BASE}/api/couple/offers/${offerId}/respond`, {
    headers: coupleHeaders(coupleToken),
    data: { response: "accept" },
  });

  if (respondRes.status() !== 200) {
    const body = await respondRes.json().catch(() => ({}));
    if (respondRes.status() !== 400 || typeof body?.error !== "string" || !body.error.includes("allerede behandlet")) {
      throw new Error(`Failed to accept offer ${offerId}: ${respondRes.status()} ${JSON.stringify(body)}`);
    }
  }

  const verifyVendorOffersRes = await request.get(`${BASE}/api/vendor/offers`, {
    headers: vendorHeaders(vendorToken),
  });
  if (verifyVendorOffersRes.status() !== 200) {
    throw new Error(`Failed to verify vendor offers: ${verifyVendorOffersRes.status()}`);
  }

  const verifyVendorOffers = await verifyVendorOffersRes.json() as Array<{
    id: string;
    status: string;
    couple?: { id?: string } | null;
  }>;
  const verified = verifyVendorOffers.find((offer) => offer.id === offerId && offer.status === "accepted" && offer.couple?.id === coupleId);
  if (!verified) {
    throw new Error(`Offer ${offerId} is not accepted for couple ${coupleId}`);
  }

  return offerId;
}

test.describe('Evendi Music Matcher MVP', () => {
  let coupleToken = '';
  let coupleId = '';
  let vendorToken = '';
  let acceptedOfferId = '';

  test.beforeAll(async ({ request }) => {
    const coupleAuth = await getCoupleAuth(request);
    coupleToken = coupleAuth.token;
    coupleId = coupleAuth.coupleId;
    vendorToken = await getVendorToken(request);
    acceptedOfferId = await ensureAcceptedOffer({
      request,
      coupleToken,
      coupleId,
      vendorToken,
    });
  });

  test('couple matcher profile + moments + recommendations endpoints', async ({ request }) => {
    const profileRes = await request.get(`${BASE}/api/couple/music/matcher/profile`, {
      headers: coupleHeaders(coupleToken),
    });

    if (profileRes.status() === 404) {
      test.skip(true, 'music_matcher_v1 is disabled in this environment');
    }

    expect(profileRes.status()).toBe(200);
    const profile = await profileRes.json();
    expect(Array.isArray(profile.preferredCultures)).toBe(true);
    expect(Array.isArray(profile.preferredLanguages)).toBe(true);
    expect(Array.isArray(profile.selectedMoments)).toBe(true);

    const momentsRes = await request.get(`${BASE}/api/couple/music/matcher/moments`, {
      headers: coupleHeaders(coupleToken),
    });
    expect(momentsRes.status()).toBe(200);
    const moments = await momentsRes.json();
    expect(Array.isArray(moments)).toBe(true);

    const candidateMoments = Array.isArray(profile.selectedMoments) && profile.selectedMoments.length > 0
      ? profile.selectedMoments.slice(0, 2)
      : moments.slice(0, 2).map((moment: { key: string }) => moment.key);

    const recRes = await request.post(`${BASE}/api/couple/music/matcher/recommendations`, {
      headers: coupleHeaders(coupleToken),
      data: {
        moments: candidateMoments,
        limitPerMoment: 10,
      },
    });

    expect(recRes.status()).toBe(200);
    const recBody = await recRes.json();
    expect(recBody.profile).toBeDefined();
    expect(recBody.recommendations).toBeDefined();
  });

  test('couple set CRUD + share-links export', async ({ request }) => {
    const createSetRes = await request.post(`${BASE}/api/couple/music/sets`, {
      headers: coupleHeaders(coupleToken),
      data: {
        title: 'E2E Music Matcher Set',
        description: 'Created by e2e test',
      },
    });

    if (createSetRes.status() === 404) {
      test.skip(true, 'music_matcher_v1 is disabled in this environment');
    }

    expect(createSetRes.status()).toBe(201);
    const createdSet = await createSetRes.json();
    const setId = createdSet.id as string;
    expect(setId).toBeTruthy();

    const addItemRes = await request.post(`${BASE}/api/couple/music/sets/${setId}/items`, {
      headers: coupleHeaders(coupleToken),
      data: {
        title: 'E2E Song',
        artist: 'E2E Artist',
        youtubeVideoId: 'dQw4w9WgXcQ',
        momentKey: 'afterparty_peak',
        dropMarkerSeconds: 45,
      },
    });
    expect(addItemRes.status()).toBe(201);
    const firstItem = await addItemRes.json();
    const firstItemId = firstItem.id as string;
    expect(firstItemId).toBeTruthy();

    const addSecondItemRes = await request.post(`${BASE}/api/couple/music/sets/${setId}/items`, {
      headers: coupleHeaders(coupleToken),
      data: {
        title: 'E2E Song 2',
        artist: 'E2E Artist 2',
        youtubeVideoId: '3JZ_D3ELwOQ',
        momentKey: 'groom_entry_mehndi',
      },
    });
    expect(addSecondItemRes.status()).toBe(201);
    const secondItem = await addSecondItemRes.json();
    const secondItemId = secondItem.id as string;
    expect(secondItemId).toBeTruthy();

    const patchItemRes = await request.patch(`${BASE}/api/couple/music/sets/${setId}/items/${firstItemId}`, {
      headers: coupleHeaders(coupleToken),
      data: {
        dropMarkerSeconds: 60,
      },
    });
    expect(patchItemRes.status()).toBe(200);

    const reorderRes = await request.patch(`${BASE}/api/couple/music/sets/${setId}/reorder`, {
      headers: coupleHeaders(coupleToken),
      data: {
        orderedItemIds: [secondItemId, firstItemId],
      },
    });
    expect(reorderRes.status()).toBe(200);

    const setsRes = await request.get(`${BASE}/api/couple/music/sets`, {
      headers: coupleHeaders(coupleToken),
    });
    expect(setsRes.status()).toBe(200);
    const sets = await setsRes.json();
    const updatedSet = sets.find((entry: { id: string }) => entry.id === setId);
    expect(updatedSet).toBeTruthy();
    expect(Array.isArray(updatedSet.items)).toBe(true);
    expect(updatedSet.items[0].id).toBe(secondItemId);

    const shareRes = await request.post(`${BASE}/api/couple/music/export/share-links`, {
      headers: coupleHeaders(coupleToken),
      data: { setId },
    });
    expect(shareRes.status()).toBe(200);
    const shareBody = await shareRes.json();
    expect(shareBody.setId).toBe(setId);
    expect(Array.isArray(shareBody.links)).toBe(true);
    expect(shareBody.totalLinks).toBeGreaterThanOrEqual(2);

    const deleteFirstItemRes = await request.delete(`${BASE}/api/couple/music/sets/${setId}/items/${firstItemId}`, {
      headers: coupleHeaders(coupleToken),
    });
    expect(deleteFirstItemRes.status()).toBe(200);

    const deleteSecondItemRes = await request.delete(`${BASE}/api/couple/music/sets/${setId}/items/${secondItemId}`, {
      headers: coupleHeaders(coupleToken),
    });
    expect(deleteSecondItemRes.status()).toBe(200);
  });

  test('couple vendor-permissions GET + PUT roundtrip', async ({ request }) => {
    const permissionsRes = await request.get(`${BASE}/api/couple/music/vendor-permissions`, {
      headers: coupleHeaders(coupleToken),
    });

    if (permissionsRes.status() === 404) {
      test.skip(true, 'music_matcher_v1 is disabled in this environment');
    }

    expect(permissionsRes.status()).toBe(200);
    const currentPermissions = await permissionsRes.json();
    expect(Array.isArray(currentPermissions)).toBe(true);

    expect(acceptedOfferId).toBeTruthy();

    const putRes = await request.put(`${BASE}/api/couple/music/vendor-permissions/${acceptedOfferId}`, {
      headers: coupleHeaders(coupleToken),
      data: { canExportYoutube: true },
    });
    expect(putRes.status()).toBe(200);
    const updated = await putRes.json();
    expect(updated.offerId).toBe(acceptedOfferId);
    expect(updated.canExportYoutube).toBe(true);

    const verifyRes = await request.get(`${BASE}/api/couple/music/vendor-permissions`, {
      headers: coupleHeaders(coupleToken),
    });
    expect(verifyRes.status()).toBe(200);
    const verifyBody = await verifyRes.json();
    const persisted = verifyBody.find((row: { offerId: string }) => row.offerId === acceptedOfferId);
    expect(persisted).toBeTruthy();
    expect(persisted.canExportYoutube).toBe(true);
  });

  test('vendor export is blocked without consent', async ({ request }) => {
    expect(acceptedOfferId).toBeTruthy();
    const setCreateRes = await request.post(`${BASE}/api/couple/music/sets`, {
      headers: coupleHeaders(coupleToken),
      data: {
        title: 'E2E Vendor Export Block',
        description: 'Consent blocked scenario',
        offerId: acceptedOfferId,
      },
    });
    expect(setCreateRes.status()).toBe(201);
    const createdSet = await setCreateRes.json();
    const setId = createdSet.id as string;

    const addItemRes = await request.post(`${BASE}/api/couple/music/sets/${setId}/items`, {
      headers: coupleHeaders(coupleToken),
      data: {
        title: 'Consent Block Song',
        artist: 'E2E',
        youtubeVideoId: 'dQw4w9WgXcQ',
        momentKey: 'afterparty_peak',
      },
    });
    expect(addItemRes.status()).toBe(201);

    const revokeRes = await request.put(`${BASE}/api/couple/music/vendor-permissions/${acceptedOfferId}`, {
      headers: coupleHeaders(coupleToken),
      data: { canExportYoutube: false },
    });
    expect(revokeRes.status()).toBe(200);

    const exportRes = await request.post(`${BASE}/api/vendor/music/export/youtube-playlist/${acceptedOfferId}`, {
      headers: vendorHeaders(vendorToken),
      data: {
        setId,
        title: 'Blocked export',
        idempotencyKey: `e2e-blocked-${Date.now()}`,
      },
    });
    expect(exportRes.status()).toBe(403);
    const exportBody = await exportRes.json();
    expect(typeof exportBody.error).toBe('string');
  });

  test('youtube connect-url + disconnect endpoints respond', async ({ request }) => {
    const connectRes = await request.get(`${BASE}/api/couple/music/youtube/connect-url`, {
      headers: coupleHeaders(coupleToken),
    });

    if (connectRes.status() === 404) {
      test.skip(true, 'music_matcher_v1 is disabled in this environment');
    }

    expect([200, 500]).toContain(connectRes.status());
    if (connectRes.status() === 200) {
      const body = await connectRes.json();
      expect(typeof body.url).toBe('string');
      expect(body.url).toContain('accounts.google.com');
    }

    const disconnectRes = await request.post(`${BASE}/api/couple/music/youtube/disconnect`, {
      headers: coupleHeaders(coupleToken),
    });
    expect([200, 404]).toContain(disconnectRes.status());
  });

  test('vendor music preferences endpoint returns matcher payload for accepted offer', async ({ request }) => {
    expect(acceptedOfferId).toBeTruthy();

    const prefsRes = await request.get(`${BASE}/api/vendor/music/preferences/${acceptedOfferId}`, {
      headers: vendorHeaders(vendorToken),
    });

    if (prefsRes.status() === 404) {
      test.skip(true, 'music_matcher_v1 is disabled in this environment');
    }

    expect(prefsRes.status()).toBe(200);
    const body = await prefsRes.json();
    expect(body).toHaveProperty('matcherProfile');
    expect(Array.isArray(body.sets)).toBe(true);
    expect(Array.isArray(body.moments)).toBe(true);
  });
});
